# Site settings
title                 : "Kenneth Chang"
title_separator       : "|"
description           : >-
                        My personal website, blog and depository of random thoughts.
                        
logo                  : "/assets/Banner_Test.jpg"
url                   : "https://scryvener.github.io/"
repository            : "scryvener/scryvener.github.io"
site.locale           : "en-US"
timezone              : "America/Los_Angeles"

theme: jekyll-theme-slate
include               :
                        - _pages

defaults              :
  # _pages
  - scope             :
      path            : ""
      type            : "pages"
      layout          : default
    values            :
      author_profile  : true
      read_time       : false
      comments        : false
      share           : false
      related         : false


