# Site settings
title                 : "Justin Perona"
title_separator       : "|"
description           : >-
                        Personal website for Justin Perona.
                        Computer scientist in the San Francisco Bay Area.
logo                  : "/assets/images/site/masthead.png"
url                   : "https://perona.dev"
repository            : "jlperona/jlperona.github.io"
site.locale           : "en-US"
timezone              : "America/Los_Angeles"

# Build settings
plugins               :
                        - jekyll-github-metadata
                        - jekyll-include-cache
                        - jekyll-remote-theme
include               :
                        - _pages

# Author sidebar settings
author                :
  name                : "Justin Perona"
  avatar              : "/assets/images/site/avatar.jpg"
  bio                 : >-
                        Computer scientist in the San Francisco Bay Area.
                        Currently looking for opportunities.
  location            : "San Francisco Bay Area"
  links               :
    - label           : "GitHub"
      icon            : "fab fa-fw fa-github"
      url             : "https://github.com/jlperona"
    - label           : "LinkedIn"
      icon            : "fab fa-fw fa-linkedin-in"
      url             : "https://www.linkedin.com/in/jlperona/"

# Footer settings
footer                :
  links               :
    - label           : "GitHub"
      icon            : "fab fa-fw fa-github"
      url             : "https://github.com/jlperona"
    - label           : "LinkedIn"
      icon            : "fab fa-fw fa-linkedin-in"
      url             : "https://www.linkedin.com/in/jlperona/"

# Collections settings
collections           :
  projects            :
    output            : true
    permalink         : /:collection/:path

# Theme settings
remote_theme          : "mmistakes/minimal-mistakes@4.20.2"
minimal_mistakes_skin : "default"
breadcrumbs           : true

# Compression settings
# See http://jch.penibelst.de/ for more details
compress_html         :
  clippings           : all
  comments            : []
  endings             : []
  ignore              :
    envs              : development
  blanklines          : false
  profile             : false
  startings           : []

# Content defaults
defaults              :
  # _pages
  - scope             :
      path            : ""
      type            : "pages"
    values            :
      layout          : single
      author_profile  : true
      read_time       : false
      comments        : false
      share           : false
      related         : false
  # _projects
  - scope             :
      path            : ""
      type            : "projects"
    values            :
      layout          : single
      author_profile  : true
      read_time       : false
      comments        : false
      share           : false
      related         : false
